# Finds the EASYLOGGING library

if(NOT EASYLOGGING_PACKAGE_DIR)
	message("ERROR: EASYLOGGING_PACKAGE_DIR requires to be set")
endif(NOT EASYLOGGING_PACKAGE_DIR)

set(EASYLOGGING_INCLUDE_DIR ${EASYLOGGING_PACKAGE_DIR})
set(EASYLOGGING_LIBRARY )

include_directories(${EASYLOGGING_INCLUDE_DIR})

if(EASYLOGGING_PACKAGE_DIR AND EASYLOGGING_INCLUDE_DIR)
	set(EASYLOGGING_FOUND "YES")
    message(STATUS "Found EASYLOGGING!")
endif(EASYLOGGING_PACKAGE_DIR AND EASYLOGGING_INCLUDE_DIR)